### ISSUE TITLE
Tester: @hjoseph10 Developer: @nikhillondhe9 HelloWorld MinSDK = 14

### ISSUE THREAD

**Issue by hjoseph10** [paceuniversity/cs6392017#1]
I am Hassan Joseph and I tested the app of @nikhillondhe9.
The Min and Target versions of the SDKs are 14 and 23 respectively. 
I tested the app on a Samsung Galaxy S7 Edge phone with android 7.0. 
The app does not crash.
The app displays:
_Hello Nikhil Londhe!
And
Welcome in CS 639 Summer 2017_
The name of the student is displayed.
The only thing I would modify is to center the text.

**Comment by scharffc** [comment]
@hjoseph10 @nikhillondhe9

Please cite each others. 

I get all the notifications but you may not!
