### ISSUE TITLE
Tester: Andrew Southard Developer: Nikhil Londhe ASyncTaskProject

### ISSUE THREAD

**Issue by andrewsouthard1** [paceuniversity/cs6392017#14]
I couldn't get the app to work on my system, below is the error message I was receiving below:

<img width="300" alt="screen shot 2017-06-20 at 7 05 17 pm" src="https://user-images.githubusercontent.com/11426477/27359765-90545a50-55eb-11e7-9b55-c11db5f3209b.png">

**Comment by nikhillondhe9** [comment]
Hi, Thank you for your review. I do not understand what exatcly the issue is. The app is working fine on my device and the emulator as well. 
![image](https://user-images.githubusercontent.com/18551507/27363445-aa43c664-5602-11e7-9818-501722c5ff88.png)

**Comment by scharffc** [comment]
What does the LogCat say?
