### ISSUE TITLE
Tester: Hassan Joseph, Developer: @andrewsouthard1, CurveMotionExercise Min SDK 21 - Target SDK 26

### ISSUE THREAD

**Issue by hjoseph10** [paceuniversity/cs6392017#19]
I am Hassan Joseph and I tested the app of Andrew Southard @andrewsouthard1.
The code is available at: https://github.com/andrewsouthard1/CS6392017/tree/master/CrvedMotionExercise.
The Min and Target versions of the SDKs are 21 and 26 respectively.
I tested the app on a Samsung Galaxy S8 phone with android 7.0.
The app does not crash.
The app successfully shows as few donuts moving in a curved motion at the click of a button in both portrait and landscape mode.

**Comment by scharffc** [comment]
Cool to have chosen flying donuts!

**Comment by andrewsouthard1** [comment]
Thanks!
