### ISSUE TITLE
Tester: Prasad Patil: Andrew HelloWorld

### ISSUE THREAD

**Issue by Sagarpatil3339** [paceuniversity/cs6392017#2]
I am Prasad Patil and I tested the app of Andrew Southard.
The Min and Target versions of the SDKs are ice-cream sandwich and Marshmellow. 
I tested the app on a phone (Samsung galaxy j7(2016) with OS Marshmellow. 
The app does not crash.
The app does display:
Hello Andrew Southard
And
Welcome in CS 639 Summer 2017

The name of the student is displayed.

The app works just as required.

**Comment by scharffc** [comment]
@Sagarpatil3339 Try to cite Andrew.

@andrewsouthard1

I prefer numbers for versions as this is what is used in Android.
