### ISSUE TITLE
ImageViewer - ChristopherRoura'S ImageViewer review by Evan Maroge

### ISSUE THREAD

**Issue by ba87688** [paceuniversity/cs6392017#29]
I am <Evan Maroge> and I tested the app of <Christopher Roura>.
The target SDK was not provided by <Christopher Roura>.
The minimum SDK was not provided by <Christopher Roura>.
The code is available at: < https://github.com/cjroura/CS6392018 of GitHub>.
The code, the apk and the 2 screenshots are available at the right location in the GitHub repository. If not, please list the problems.
The topic of the app is <Dogs>.
The code uses use fragments.
The images of the app are available in different formats. List the formats (e.g., xhdpi).
I tested the app on emulator(s) with OS <8.0 nugget>.
The app does not crashes.
The images appear appear well.
There are 5 images.
Please mention all the problems with the app, what should be improved, and put a general comment. The best thing is to create screenshots to showcase the problems (with explanations).
One problem is that the images are too small. Also, the last image is cut out. You should have used a scrollview.

**Comment by scharffc** [comment]
@ba87688 This issue is not an issue of https://github.com/paceuniversity/cs6392017/ but the issue of a specific app for a specific student. It should be in his/her issue tracker. It needs to posted there asap. I am checking today and if it is not there will not be able to give you credit.

**Comment by scharffc** [comment]
@ba87688 The topic of app is missing.  The code disappeared from github. You need to spend some time in figuring out git and github.

@cjroura
