### ISSUE TITLE
HelloWorld - Christopher Roura's HelloWorld Test/Review by Evan Maroge

### ISSUE THREAD

**Issue by ba87688** [paceuniversity/cs6392017#30]
I am <Evan Maroge> and I tested the app of <Christopher Roura>. The Min and Target versions of the SDKs are <15> and <28>.
I tested the app on a phone emulator with OS Nugget <8.0>.
The app does not crash.
The app does display:
Hello Christopher Roura
And
Welcome in CS 639 Summer 2018
The name of the student is displayed.

**Comment by scharffc** [comment]
@ba87688 This issue is not an issue of https://github.com/paceuniversity/cs6392017/ but the issue of a specific app for a specific student. It should be in his/her issue tracker. It needs to posted there asap. I am checking today and if it is not there will not be able to give you credit.
