### ISSUE TITLE
ImageViewer - Tester: Kritin Kondru, Developer: Ankita Jawale, ImageViewer

### ISSUE THREAD

**Issue by kritkondru** [paceuniversity/cs6392017#33]
I am Kritin and I tested the app of Ankita.
The target SDK was 27.
The minimum SDK was 15.
The code is available at: https://github.com/ankijaws/CS6392018.
The code, the apk and the 2 screenshots are available at the right location in the GitHub repository.
The topic of the app is Cities in USA.
The code uses fragments.
The images of the app are available in different formats hdpi,mdpi,xhdpi,xxhdpi and xxxhdpi .
I tested the app on emulator(s) with OS marshmallow (6.0),kitkat (4.0),Lollipop (5.0).
The app doesnt crash.
The images appear well.
There are 5 images.
There was no problem for me with running the app and I have run it in 3 versions of OS and I have seen that you have used linear layout

**Comment by scharffc** [comment]
@kritkondru 

@ankijaws Some of the images are very big, even mdpi. They would even be too big for the largest phone screen.

Use the SDKs instead of anything else.
