### ISSUE TITLE
ImageViewer - Tester: Geetha Lakkarasu, Developer: Andi Maroge, ImageViewer

### ISSUE THREAD

**Issue by LakkarasuGeetha** [paceuniversity/cs6392017#34]
I am Geetha Lakkarasu and I tested the app of Andi Maroge.
The target SDK was not provided by Andi.
The minimum SDK was not provided by Andi.
The code is available at: https://github.com/Amaroge3/CS6392018
The code, the apk and the 2 screenshots are available at the right location in the GitHub repository.
The topic of the app is Las Vegas Trip Pictures.
The code uses fragments.
The images of the app are available in different formats. List the formats (hdpi, mdpi, xhdpi, xxhdpi, xxxhdpi).
I tested the app on emulator(s) with OS KitKat 4.0.2 and Marshmallow 6.0.1.
The app crashes in KitKat version.
The images appear well .
There are 5 images.

App doesn't get installed in Kitkat OS where as in Marshmallow the app runs pretty well. You could make use of wrap_content for the height and width of imageview.

**Comment by scharffc** [comment]
@LakkarasuGeetha We need the exact URL. Instead of saying kitkat etc also use the API number as tis is the way that it is done in gradle.

@Amaroge3 Min SDK should be a number?

@Amaroge3 Why does the app crashed on KitKat?
