### ISSUE TITLE
AsyncTask -Tester: Sonal Sahu, Developer: Tejasvini Shelar, AsyncTaskProject, Min SDK: 19. 

### ISSUE THREAD

**Issue by sonal-sahu** [paceuniversity/cs6392017#46]
I am Sonal Sahu and I tested the app of Tejasvini Shelar. @tejasvinishelar
The code is available at: https://github.com/sonal-sahu/CS6392018/tree/master/AsyncTaskProject
The minimum SDK is 19.
The target SDK is 27.
The code, the apk and a screenshot are available at the right location in the GitHub repository.
The image link-https://github.com/tejasvinishelar/CS6392018/blob/master/Chandvad.jpg
Image file location https://raw.githubusercontent.com/tejasvinishelar/CS6392018/master/Chandvad.jpg
The code uses fragments as there is content_main.xml,MainActivityFragment.java and fragment_main.xml file.
The app has been personalized by the student with an image of her place of birth.
The selected image is available in all format (hdpi, xhdpi etc).
I have tested the app on different emulators like Nexus 7,Pixel API 23,5.4 FWVGA API 23,Nexus S API 23 with Android 6.0 (Marshmallow) both in landscape and portrait mode.Please
find the below snapshots.
<img width="569" alt="test1" src="https://user-images.githubusercontent.com/38184732/41775867-ac9c4190-75f3-11e8-8097-4debf1181b66.PNG">
<img width="434" alt="test2" src="https://user-images.githubusercontent.com/38184732/41775876-b4f39582-75f3-11e8-82e7-42e41f12a92e.PNG">

The app does not crashes.
The application is working fine as expected on all emulators when checked with different density formats like hdpi,xhdpi,etc.
I noticed that Application title is not getting displayed but i thought the required functionality is working fine so app not displaying title can work.

**Comment by scharffc** [comment]
@sonal-sahu You did not test Tejasvini
