### ISSUE TITLE
AsyncTask -Tester: Tejasvini Shelar, Developer: Sonal Sahu, AsyncTaskProject, Min SDK: 23. 

### ISSUE THREAD

**Issue by tejasvinishelar** [paceuniversity/cs6392017#47]
I am Tejasvini Shelar and I tested the app of Sonal Sahu. @sonal-sahu 
The code is available at: https://github.com/sonal-sahu/CS6392018/tree/master/AsyncTaskProject.
The minimum SDK is 23.
The target SDK is 27.
The code, the apk and a screenshot are available at the right location in the GitHub repository.
The code use fragments.
The app has been personalized by the student with an image of her place of birth.
The selected image is available in all format (hdpi, xhdpi etc).
I tested the app on phones and tablet emulators with OS Android 8.1-Oreo and 6.0-Marshmallow. 
The app does not crashes.
The application is working fine as expected on all emulators with different image formats.

**Comment by scharffc** [comment]
@tejasvinishelar Sonal not cited
