### ISSUE TITLE
AsyncTask -Tester: Ankita Jawale, Developer: Kevin Delgado, AsyncTaskProject, Min SDK: 19. 

### ISSUE THREAD

**Issue by ankijaws** [paceuniversity/cs6392017#49]
I am Ankita Jawale and I tested the app of Kevin Delgado @kd90693n
The code is available at: https://github.com/kd90693n/CS6392018/tree/master/AsyncTaskProject
The minimum SDK is 19.
The target SDK is 27.
The code, the apk and a screenshot are available at the right location in the GitHub repository. 
The code uses fragments.
The app has been personalized by the student with an image of his place of birth.
The selected image is not available in all format.
I tested the app on phone and emulator with OS Android 4.4.4 and Android 6.0.1 
The app does not crashes.

I liked the way you have written the text about your place of birth. Also i can see that you have used ScrollView so as to avoid the display issue in Landscape mode. 
But I can see that you have given hardcoded values for the height and width of ImageView. Instead you can practice using wrap_content / match_parent which ever needed.

**Comment by scharffc** [comment]
@ankijaws Kevin not cited!
