### ISSUE TITLE
Tester: Andrew Southard, Developer: Prasad, ImageViewer

### ISSUE THREAD

**Issue by andrewsouthard1** [paceuniversity/cs6392017#5]
I am Andrew Southard and I tested the app of Prasad
The target SDK was provided by Prasad.
The minimum SDK was provided by Prasad.
The code is available at: https://github.com/Sagarpatil3339/CS6392017
The code, the apk are available in the right location, there were no screenshots.
The topic of the app is New York.
The code uses fragments.
The images of the app are available in different formats, xxxhdpi, xxhdpi, xhdpi, hdpi, mdpi
The tested the app on emulator on my Mac
The app does not crash
The images appear well
There are 5 images

App works very smoothly, great job Prasad!

<img width="400" alt="screen shot 2017-06-14 at 2 10 13 pm" src="https://user-images.githubusercontent.com/11426477/27147565-3e725c62-510b-11e7-8132-90b1bfebceb7.png">
<img width="599" alt="screen shot 2017-06-14 at 2 10 21 pm" src="https://user-images.githubusercontent.com/11426477/27147571-40858ede-510b-11e7-8f74-c14687dafb84.png">

**Comment by scharffc** [comment]
@andrewsouthard1 @Sagarpatil3339

The drawables do not seem correct and the testing either. By looking at the code I do see only one resolution for the pic. I think you need to read the slides on images. We should not have 5 times the same pic on the screen with different dimensions but 5 different pics with 5 different resolutions and in the right directories. 

https://github.com/Sagarpatil3339/CS6392017/tree/master/ImageViewer/app/src/main/res/drawable
