### ISSUE TITLE
AsyncTask -Tester: Dalem, Developer: Kritin, AsyncTaskProject, Min SDK: 23

### ISSUE THREAD

**Issue by TDAAPaceUni** [paceuniversity/cs6392017#50]
I am Dalem and I tested the app of Kritin.
The code is available at: https://github.com/kritkondru/CS6392018/tree/master/AsyncTaskProject
The minimum SDK is 23.
The target SDK is 27.
The code, the APK, and the screenshot are available in the right location in the GitHub.
The code uses fragments.
The app has been personalized by the student with an image of the place of birth.
The selected image is available in all formats.
I tested the app on my Samsung Galaxy S7 Edge with Android 8.0 and my Samsung Galaxy Tab S2 with Android 7.0.
The app does not crash.
The app has no problems and works as intended. There is a nice varying set of pictures.

**Comment by scharffc** [comment]
@TDAAPaceUni Kritin not cited.
