### ISSUE TITLE
AsyncTask -Tester:Kritin Kondru, Developer: Dalem, AsyncTaskProject, Min SDK: 15. 

### ISSUE THREAD

**Issue by kritkondru** [paceuniversity/cs6392017#51]
I am Kritin Kondru and I tested the app of Tjok Dalem
The code is available at: https://github.com/TDAAPaceUni/CS6392018.
The minimum SDK is 15.
The target SDK is 27.
The code, the apk and a screenshot are available at the right location in the GitHub repository.
The code use fragments.
The app has been personalized by the student with an image of his/her place of birth.
The selected image is available in all format (hdpi, xhdpi etc).
I tested the app on  emulator(s) with OS 4.0. 
The app does not crash .
The app works well on the emulator on OS 4.0.

**Comment by scharffc** [comment]
@kritkondru Dalem not cited.
