### ISSUE TITLE
AsyncTask -Tester: Geetha Lakkarasu, Developer: Christopher Roura, AsyncTaskProject, Min SDK: XXX. 

### ISSUE THREAD

**Issue by LakkarasuGeetha** [paceuniversity/cs6392017#52]
The project is not available on Christopher Roura's @cjroura GitHub account. So couldn't review and give feedback for his AsyncTaskProject.

**Comment by scharffc** [comment]
@LakkarasuGeetha 

Christopher is NOT cited here. 

Did he submit or not? 

Why would you use the template if he did not submit. Your issue should only be that he did not submit and you should cite him here. 

Please do asap.
