### ISSUE TITLE
Tester: @hjoseph10 Developer: @nikhillondhe9 ImageViewer MinSDK = 19

### ISSUE THREAD

**Issue by hjoseph10** [paceuniversity/cs6392017#7]
I am Hassan Joseph and I tested the app of @nikhillondhe9.
The target SDK was provided by @nikhillondhe9.
The minimum SDK was provided by @nikhillondhe9.
The code is available at: https://github.com/nikhillondhe9/CS6392017/tree/master/ImageViewer.
The code, the apk and the 2 screenshots are available at the right location in the GitHub repository. 
The topic of the app is Dog.
The code use fragments.
I am not sure if they are available in different format because I don’t see the different drawable folders.
I tested the app on a Samsung Galaxy S7 Edge phone with android 7.0.
The app crashes.

**Comment by scharffc** [comment]
@nikhillondhe9

The drawable folders are not available. This needs to be fixed.
