### ISSUE TITLE
Tester: Prasad, Developer: Andrew Southard, ImageViewer

### ISSUE THREAD

**Issue by Sagarpatil3339** [paceuniversity/cs6392017#9]
I am Prasad and I tested the app of Andrew Southard
The target SDK was provided by Andrew Southard.
The minimum SDK was provided by Andrew Southard.
The code is available at: https://github.com/andrewsouthard1/CS6392017
The code, the apk are available in the right location, there were screenshots.
The topic of the app is Dogs.
The code do not uses fragments.
The images of the app are available in different formats, xxxhdpi, xxhdpi, xhdpi, hdpi, mdpi
I tested the app on emulator on my Mac
The app does not crash
The images appear well
There are 5 images
No Problems encountered while running
App works very smoothly, great job Andrew!
![screen shot 2017-06-15 at 7 03 32 pm](https://user-images.githubusercontent.com/20169646/27183987-3f37fdc0-51fe-11e7-90b4-61b318c67cf6.png)
![screen shot 2017-06-15 at 7 02 42 pm](https://user-images.githubusercontent.com/20169646/27184004-4c06d148-51fe-11e7-9054-204a05f7fc73.png)

**Comment by scharffc** [comment]
@Sagarpatil3339 

Please cite the name of the person of the project you are testing.

Is this really correct? The image files are not in the correct directory. Please see the lecture on images. This is very badly explained on the web and I made it clear in the slides.

@andrewsouthard1
